// WISEcon27 — Certificate of attendance / CPD. Lists the sessions the delegate
// added to their schedule (our best proxy for "attended"), totals the contact
// hours, and offers a print-to-PDF of a formal certificate. Everything is
// derived on the device; nothing extra is stored.
import { T, TABBAR_H } from '../theme'
import type { AppCtx } from '../appState'
import type { Session } from '../types'
import { Icon } from '../components/Icon'
import { AppHeader, Btn, Empty, Eyebrow } from '../components/primitives'
import { useT } from '../i18n'

const minutesOf = (s: Session) => {
  const toMin = (t: string) => {
    const [h, m] = t.split(':').map((n) => parseInt(n, 10))
    return (h || 0) * 60 + (m || 0)
  }
  return Math.max(0, toMin(s.end) - toMin(s.start))
}

const fmtHours = (mins: number) => {
  const h = mins / 60
  return (Number.isInteger(h) ? h.toString() : h.toFixed(1))
}

export function Certificate({ ctx }: { ctx: AppCtx }) {
  const { t } = useT()
  const me = ctx.me
  const attended = ctx.sessions
    .filter((s) => ctx.isBookmarked(s.id) && s.type !== 'break' && s.type !== 'social')
    .sort((a, b) => (a.day + a.start).localeCompare(b.day + b.start))
  const totalMin = attended.reduce((n, s) => n + minutesOf(s), 0)
  const dateLabel = ctx.event.dateline || ''

  const print = () => {
    const rows = attended
      .map((s) => {
        const day = ctx.days.find((d) => d.id === s.day)
        const when = [day ? `${day.dow} ${day.date}` : '', `${s.start}–${s.end}`].filter(Boolean).join(', ')
        return `<tr><td>${escapeHtml(s.title)}</td><td class="when">${escapeHtml(when)}</td></tr>`
      })
      .join('')
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>Certificate of attendance — ${escapeHtml(me.name)}</title>
      <style>
        *{box-sizing:border-box} body{font-family:'Signika',Arial,sans-serif;color:#1a1a1a;margin:0;padding:48px}
        .frame{border:3px solid #769b08;border-radius:14px;padding:44px 48px;max-width:760px;margin:0 auto}
        .brand{font-weight:700;letter-spacing:.04em;text-transform:uppercase;color:#769b08;font-size:13px}
        h1{font-size:30px;margin:18px 0 4px} .sub{color:#555;font-size:14px;margin-bottom:28px}
        .name{font-size:26px;font-weight:700;margin:6px 0} .meta{color:#555;font-size:14px;margin-bottom:24px}
        .stat{display:inline-block;margin-right:32px} .stat b{font-size:22px;color:#769b08} .stat span{display:block;color:#666;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
        table{width:100%;border-collapse:collapse;margin-top:18px;font-size:13px}
        td{padding:8px 0;border-bottom:1px solid #eee;vertical-align:top} .when{text-align:right;color:#666;white-space:nowrap;padding-left:16px}
        .foot{margin-top:32px;color:#888;font-size:12px}
      </style></head><body>
      <div class="frame">
        <div class="brand">WISEcon27 · Powered by UNIwise</div>
        <h1>${escapeHtml(t('cert.title'))}</h1>
        <div class="sub">${escapeHtml(t('cert.presented'))}</div>
        <div class="name">${escapeHtml(me.name)}</div>
        <div class="meta">${escapeHtml([me.role, me.org].filter(Boolean).join(' · '))}</div>
        <div class="sub">${escapeHtml(t('cert.attended'))} WISEcon27${dateLabel ? ', ' + escapeHtml(dateLabel) : ''}${ctx.event.location ? ' · ' + escapeHtml(ctx.event.location) : ''}.</div>
        <div style="margin:8px 0 4px">
          <div class="stat"><b>${fmtHours(totalMin)}</b><span>${escapeHtml(t('cert.cpd'))}</span></div>
          <div class="stat"><b>${attended.length}</b><span>${escapeHtml(t('cert.sessions'))}</span></div>
        </div>
        <table>${rows}</table>
        <div class="foot">Generated by the WISEcon27 app on ${new Date().toLocaleDateString()}.</div>
      </div>
      <script>window.onload=function(){setTimeout(function(){window.print()},250)}</script>
    </body></html>`
    // print via a sandboxed iframe — survives popup blockers and PWA standalone
    const iframe = document.createElement('iframe')
    iframe.style.position = 'fixed'
    iframe.style.right = '0'
    iframe.style.bottom = '0'
    iframe.style.width = '0'
    iframe.style.height = '0'
    iframe.style.border = '0'
    document.body.appendChild(iframe)
    const doc = iframe.contentWindow?.document
    if (doc) {
      doc.open()
      doc.write(html)
      doc.close()
      setTimeout(() => document.body.removeChild(iframe), 60000)
    } else {
      document.body.removeChild(iframe)
      ctx.toast('Printing is not available on this device')
    }
  }

  return (
    <div>
      <AppHeader title={t('cert.title')} onBack={ctx.back} />
      <div style={{ padding: '14px 16px ' + (TABBAR_H + 16) + 'px' }}>
        <p style={{ fontFamily: T.sig, fontSize: 14.5, color: T.muted, lineHeight: 1.5, marginBottom: 16 }}>{t('cert.subtitle')}</p>

        {attended.length === 0 ? (
          <Empty icon="shield" text={t('cert.none')} />
        ) : (
          <>
            {/* summary card */}
            <div style={{ background: 'var(--wf-surface)', borderRadius: 'var(--radius-5)', boxShadow: 'var(--shadow-card)', padding: 18, marginBottom: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14 }}>
                <div style={{ width: 44, height: 44, borderRadius: '50%', background: T.green1, color: T.green10, display: 'grid', placeItems: 'center', flexShrink: 0 }}>
                  <Icon name="shield" size={22} />
                </div>
                <div>
                  <div style={{ fontFamily: T.sig, fontWeight: 700, fontSize: 17, color: T.ink }}>{me.name}</div>
                  <div style={{ fontFamily: T.sig, fontSize: 13, color: T.muted }}>{[me.role, me.org].filter(Boolean).join(' · ')}</div>
                </div>
              </div>
              <div style={{ display: 'flex', gap: 12 }}>
                <Stat n={fmtHours(totalMin)} label={t('cert.cpd')} />
                <Stat n={String(attended.length)} label={t('cert.sessions')} />
              </div>
            </div>

            {/* session list */}
            <Eyebrow style={{ paddingLeft: 4, marginBottom: 8 }}>{t('cert.sessions')}</Eyebrow>
            <div style={{ background: 'var(--wf-surface)', borderRadius: 'var(--radius-5)', boxShadow: 'var(--shadow-card)', overflow: 'hidden', marginBottom: 18 }}>
              {attended.map((s, i) => {
                const day = ctx.days.find((d) => d.id === s.day)
                return (
                  <div key={s.id} style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '13px 16px', borderBottom: i === attended.length - 1 ? 'none' : '1px solid ' + T.line }}>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontFamily: T.sig, fontWeight: 600, fontSize: 14.5, color: T.ink, lineHeight: 1.3 }}>{s.title}</div>
                      <div style={{ fontFamily: T.onest, fontSize: 12, color: T.muted, marginTop: 2 }}>{day ? `${day.dow} ${day.date} · ` : ''}{s.start}–{s.end}</div>
                    </div>
                  </div>
                )
              })}
            </div>

            <Btn kind="primary" full icon="download" onClick={print}>{t('cert.download')}</Btn>
          </>
        )}
      </div>
    </div>
  )
}

function Stat({ n, label }: { n: string; label: string }) {
  return (
    <div style={{ flex: 1, background: T.sunken, borderRadius: 'var(--radius-4)', padding: '12px 14px' }}>
      <div style={{ fontFamily: T.onest, fontWeight: 700, fontSize: 24, color: T.green10, lineHeight: 1 }}>{n}</div>
      <div style={{ fontFamily: T.sig, fontSize: 11.5, color: T.muted, marginTop: 4, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{label}</div>
    </div>
  )
}

function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c))
}
